requires 'Test::APIcast', '0.24';
requires 'Crypt::JWT';
requires 'Test::Deep';
requires 'TAP::Harness::JUnit';
requires 'File::Slurp';
requires 'JSON';
requires 'URI::data';
requires 'Data::Inspect';
requires 'YAML';
