#!/bin/bash
set -euo pipefail

coverage='luacov.stats.*.out'

generate_coverage() {
  find . -maxdepth 1 -name "$coverage" -exec script/luacov '{}' \;
}
trap generate_coverage EXIT

# shellcheck disable=SC2086
rm -f $coverage luacov.report.*.out

if [ -n "${JUNIT_OUTPUT_FILE:-}" ]; then
  mkdir -p "$(dirname "$JUNIT_OUTPUT_FILE")"
fi

TMPFILE=$(mktemp) || exit 1
prove "$@" 2>&1 | tee $TMPFILE
# No need to capture exit code. set -e option instructs bash to immediately exit if any command has a non-zero exit status
if [ -n "${CI:-}" ]; then
    cat "${TMPFILE}" | awk '/found ONLY/ { print "FAIL: because found ONLY in test"; print; exit 1 }; { print }'
    status="$?"
    if [ $status -gt 0 ]; then
      echo "Failure. Exit code: ${status}"
      exit $status
    fi
fi

echo "Success"
